/* The following code was generated by JFlex 1.4.1 on 10/28/15 8:49 AM */

package com.davidmogar.njc.lexicon;

import com.davidmogar.njc.syntactic.Parser;
import com.davidmogar.njc.TypeError;
import com.davidmogar.njc.syntactic.Tokens;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 10/28/15 8:49 AM from the specification file
 * <tt>../../src/com/davidmogar/njc/lexicon/lexicon.flex</tt>
 */
public class Lexicon {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\26\1\2\1\0\1\26\1\4\22\0\1\26\1\15\1\16"+
    "\1\0\1\23\1\0\1\50\1\17\1\11\1\11\1\3\1\7\1\11"+
    "\1\10\1\24\1\1\12\5\1\0\1\11\1\12\1\14\1\13\2\0"+
    "\4\6\1\25\15\6\1\42\7\6\1\11\1\20\1\11\1\0\1\23"+
    "\1\0\1\31\1\35\1\27\1\32\1\37\1\44\1\43\1\30\1\40"+
    "\2\6\1\36\1\46\1\21\1\33\2\6\1\22\1\6\1\41\1\34"+
    "\1\47\1\45\3\6\1\11\1\51\1\11\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\2\1\3\1\4\1\5"+
    "\6\2\2\1\1\5\1\1\1\3\7\5\2\1\1\3"+
    "\1\0\1\6\1\7\1\10\1\0\1\11\1\12\1\13"+
    "\1\14\1\0\1\15\2\0\1\5\1\6\3\5\1\16"+
    "\4\5\1\17\1\20\2\0\1\21\1\0\3\5\1\22"+
    "\4\5\1\6\2\0\1\5\1\23\3\5\1\24\1\25"+
    "\3\5\1\26\1\27\1\30\1\31";

  private static int [] zzUnpackAction() {
    int [] result = new int[83];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\52\0\250\0\322\0\374"+
    "\0\u0126\0\u0150\0\u017a\0\u01a4\0\u01ce\0\u01f8\0\u0222\0\u024c"+
    "\0\u0276\0\u02a0\0\52\0\u02ca\0\u02f4\0\u031e\0\u0348\0\u0372"+
    "\0\u039c\0\u03c6\0\u03f0\0\u041a\0\u0444\0\u046e\0\u0498\0\52"+
    "\0\52\0\u02a0\0\52\0\52\0\52\0\52\0\u0222\0\52"+
    "\0\u04c2\0\u04ec\0\u0516\0\u0540\0\u056a\0\u0594\0\u05be\0\374"+
    "\0\u05e8\0\u0612\0\u063c\0\u0666\0\52\0\52\0\u0690\0\u06ba"+
    "\0\52\0\u06e4\0\u070e\0\u0738\0\u0762\0\374\0\u078c\0\u07b6"+
    "\0\u07e0\0\u080a\0\u0834\0\u0834\0\u085e\0\u0888\0\374\0\u08b2"+
    "\0\u08dc\0\u0906\0\374\0\374\0\u0930\0\u095a\0\u0984\0\374"+
    "\0\374\0\374\0\374";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[83];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\5\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\2\1\10\1\21\1\2\1\22\1\10\1\23\1\24"+
    "\2\10\1\25\5\10\1\26\1\10\1\27\2\10\1\30"+
    "\1\31\1\32\1\33\1\34\53\0\1\35\1\0\1\36"+
    "\52\0\1\23\47\0\1\23\54\0\1\7\16\0\1\37"+
    "\32\0\2\10\12\0\3\10\1\0\1\10\1\0\21\10"+
    "\11\0\1\40\47\0\1\7\2\0\1\41\13\0\1\42"+
    "\41\0\1\43\51\0\1\44\51\0\1\45\51\0\1\46"+
    "\35\0\16\47\1\50\33\47\2\51\1\0\15\51\1\52"+
    "\31\51\5\0\2\10\12\0\3\10\1\0\1\10\1\0"+
    "\10\10\1\53\10\10\7\0\1\54\51\0\2\10\12\0"+
    "\3\10\1\0\1\10\1\0\1\10\1\55\17\10\7\0"+
    "\2\10\12\0\3\10\1\0\1\10\1\0\4\10\1\56"+
    "\14\10\7\0\2\10\12\0\1\57\2\10\1\0\1\10"+
    "\1\0\15\10\1\60\3\10\7\0\2\10\12\0\3\10"+
    "\1\0\1\10\1\0\12\10\1\61\6\10\7\0\2\10"+
    "\12\0\3\10\1\0\1\10\1\0\1\10\1\62\17\10"+
    "\7\0\2\10\12\0\3\10\1\0\1\10\1\0\2\10"+
    "\1\63\16\10\7\0\2\10\12\0\3\10\1\0\1\10"+
    "\1\0\4\10\1\64\14\10\52\0\1\65\52\0\1\66"+
    "\2\35\1\0\47\35\3\36\1\67\46\36\5\0\1\37"+
    "\17\0\1\70\11\0\1\70\31\0\1\71\37\0\1\72"+
    "\11\0\1\71\1\0\2\51\34\0\2\10\12\0\3\10"+
    "\1\0\1\10\1\0\12\10\1\73\6\10\27\0\1\70"+
    "\11\0\1\70\17\0\2\10\12\0\3\10\1\0\1\10"+
    "\1\0\2\10\1\74\16\10\7\0\2\10\12\0\3\10"+
    "\1\0\1\10\1\0\5\10\1\75\13\10\7\0\2\10"+
    "\12\0\3\10\1\0\1\10\1\0\12\10\1\76\6\10"+
    "\7\0\2\10\12\0\1\10\1\77\1\10\1\0\1\10"+
    "\1\0\21\10\7\0\2\10\12\0\3\10\1\0\1\10"+
    "\1\0\11\10\1\100\7\10\7\0\2\10\12\0\3\10"+
    "\1\0\1\10\1\0\11\10\1\101\7\10\7\0\2\10"+
    "\12\0\3\10\1\0\1\10\1\0\11\10\1\102\7\10"+
    "\2\0\1\36\1\23\1\36\1\67\46\36\5\0\1\103"+
    "\2\0\1\104\46\0\1\105\51\0\2\10\12\0\3\10"+
    "\1\0\1\10\1\0\5\10\1\106\13\10\7\0\2\10"+
    "\12\0\1\10\1\107\1\10\1\0\1\10\1\0\21\10"+
    "\7\0\2\10\12\0\3\10\1\0\1\10\1\0\6\10"+
    "\1\110\12\10\7\0\2\10\12\0\3\10\1\0\1\10"+
    "\1\0\11\10\1\111\7\10\7\0\2\10\12\0\3\10"+
    "\1\0\1\10\1\0\7\10\1\112\11\10\7\0\2\10"+
    "\12\0\1\113\2\10\1\0\1\10\1\0\21\10\7\0"+
    "\2\10\12\0\3\10\1\0\1\10\1\0\3\10\1\114"+
    "\15\10\7\0\1\103\51\0\1\51\51\0\2\10\12\0"+
    "\1\10\1\115\1\10\1\0\1\10\1\0\21\10\7\0"+
    "\2\10\12\0\3\10\1\0\1\10\1\0\7\10\1\116"+
    "\11\10\7\0\2\10\12\0\1\117\2\10\1\0\1\10"+
    "\1\0\21\10\7\0\2\10\12\0\3\10\1\0\1\10"+
    "\1\0\10\10\1\120\10\10\7\0\2\10\12\0\1\121"+
    "\2\10\1\0\1\10\1\0\21\10\7\0\2\10\12\0"+
    "\3\10\1\0\1\10\1\0\10\10\1\122\10\10\7\0"+
    "\2\10\12\0\3\10\1\0\1\10\1\0\14\10\1\123"+
    "\4\10\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2478];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\15\1\1\11\12\1\1\0"+
    "\1\1\2\11\1\0\4\11\1\0\1\11\2\0\12\1"+
    "\2\11\2\0\1\11\1\0\11\1\2\0\16\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[83];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

public Object matchedText; // Semantic value of the token returned.

/**
 * Return token's column.
 */
public int getColumn() {
	return yycolumn + 1;
}

/**
 * Return token's line.
 */
public int getLine() {
	return yyline + 1;
}



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexicon(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexicon(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 134) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 17: 
          { matchedText = yytext().charAt(1); return Tokens.CHARACTER_LITERAL;
          }
        case 26: break;
        case 16: 
          { matchedText = yytext(); return Tokens.OR;
          }
        case 27: break;
        case 12: 
          { matchedText = yytext(); return Tokens.NOT_EQUALS;
          }
        case 28: break;
        case 19: 
          { matchedText = yytext(); return Tokens.CHARACTER;
          }
        case 29: break;
        case 5: 
          { matchedText = yytext(); return Tokens.IDENTIFIER;
          }
        case 30: break;
        case 9: 
          { matchedText = yytext(); return Tokens.LOWER_EQUALS;
          }
        case 31: break;
        case 2: 
          { matchedText = yycharat(0); return (int) yycharat(0);
          }
        case 32: break;
        case 24: 
          { matchedText = yytext(); return Tokens.DOUBLE;
          }
        case 33: break;
        case 4: 
          { matchedText = new Integer(yytext()); return Tokens.INTEGER_LITERAL;
          }
        case 34: break;
        case 25: 
          { matchedText = yytext(); return Tokens.STRING;
          }
        case 35: break;
        case 20: 
          { matchedText = yytext(); return Tokens.MAIN;
          }
        case 36: break;
        case 6: 
          { matchedText = new Double(yytext()); return Tokens.DOUBLE_LITERAL;
          }
        case 37: break;
        case 7: 
          { matchedText = yytext(); return Tokens.INCREMENT;
          }
        case 38: break;
        case 14: 
          { matchedText = yytext(); return Tokens.IF;
          }
        case 39: break;
        case 18: 
          { matchedText = yytext(); return Tokens.INTEGER;
          }
        case 40: break;
        case 11: 
          { matchedText = yytext(); return Tokens.EQUALS;
          }
        case 41: break;
        case 8: 
          { matchedText = yytext(); return Tokens.DECREMENT;
          }
        case 42: break;
        case 10: 
          { matchedText = yytext(); return Tokens.GREATER_EQUALS;
          }
        case 43: break;
        case 21: 
          { matchedText = yytext(); return Tokens.VOID;
          }
        case 44: break;
        case 23: 
          { matchedText = yytext(); return Tokens.RETURN;
          }
        case 45: break;
        case 22: 
          { matchedText = yytext(); return Tokens.WHILE;
          }
        case 46: break;
        case 15: 
          { matchedText = yytext(); return Tokens.AND;
          }
        case 47: break;
        case 1: 
          { new TypeError(this.getLine(), this.getColumn(),"Character \'" + yycharat(0) + "' unknown.");
          }
        case 48: break;
        case 3: 
          { 
          }
        case 49: break;
        case 13: 
          { matchedText = yytext().replaceAll("\"", ""); return Tokens.STRING_LITERAL;
          }
        case 50: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
